### ISSUE TITLE
Tests don't get properly added to the totals when ASSUME is outside of GIVEN

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#2836]
This might just be a thing of improperly made tests.

![image](https://user-images.githubusercontent.com/2904965/226060163-9243f6cd-0144-4b16-a5bf-3961c644543b.png)
![image](https://user-images.githubusercontent.com/2904965/226060400-badddbe0-2e42-4204-9c05-43717dea2835.png)

**Comment by mrgriffin** [comment]
This is possibly (hopefully! :crossed_fingers:) improved by the `estimateCost` changes in #2955.

**Comment by hedara90** [comment]
Is this issue still relevant or could it be restated?
It still seems to be a problem with `ASSUME` usage outside of  `ASSUMPTIONS` and `GIVEN`, but in a different way.
![20240822_09h38m18s_grim](https://github.com/user-attachments/assets/6ae25a53-d865-433e-aad4-95df5ecafec5)
When `ASSUME` is placed outside of `GIVEN` in a single test it generates one "ASSUME failed" per thread.
Would it be possible to make it so that `ASSUMES` places outside of `GIVEN`/`ASSUMPTIONS` fail to compile?

**Comment by AlexOn1ine** [comment]
@AsparagusEduardo this should be fixed by now, right?

**Comment by AsparagusEduardo** [comment]
> @AsparagusEduardo this should be fixed by now, right?

it is as @hedara90 said, still not fixed.
![image](https://github.com/user-attachments/assets/79ba3ed6-4f4f-4bb2-8294-940e160433c6)

> Would it be possible to make it so that ASSUMES places outside of GIVEN/ASSUMPTIONS fail to compile?

Either that or mark them as INVALID like other tests syntaxes are made

**Comment by AsparagusEduardo** [comment]
> > Would it be possible to make it so that ASSUMES places outside of GIVEN/ASSUMPTIONS fail to compile?
> Either that or mark them as INVALID like other tests syntaxes are made

I don't know how to do this though. I can make a PR that makes all ASSUMES be inside of GIVEN and we start looking for it in reviews?

**Comment by hedara90** [comment]
From what I saw when I looked through the code there was only 1 `ASSUME` that was outside `ASSUMPTIONs` or `GIVEN` blocks (in `test/random.c`).

**Comment by AsparagusEduardo** [comment]
> From what I saw when I looked through the code there was only 1 `ASSUME` that was outside `ASSUMPTIONs` or `GIVEN` blocks (in `test/random.c`).

I have the brach ready, there are a *lot* more (over 30).

**Comment by hedara90** [comment]
Ah, I kinda meant "that have to be outside"

**Comment by AsparagusEduardo** [comment]
#5308

**Comment by Bassoonian** [comment]
Tests currently still don't notify you if you have assumes outside of given, right?

**Comment by AsparagusEduardo** [comment]
They don't, no
