### ISSUE TITLE
"Only one alive mon" double battles break if slot 2 is an egg and you revive a Pokémon

### ISSUE THREAD

**Issue by luckytyphlosion** [rh-hideout/pokeemerald-expansion#5175]
### Description

Video: https://discord.com/channels/419213663107416084/774393519569502268/1273461790289825873
"the solution I'm pretty sure is to re-order the party indexes so a fainted mon is in slot 2"

### Version

1.9.0 (Latest release)

### Discord contact info

luckytyphlosion

**Comment by luckytyphlosion** [comment]
Possible solution: 
- Remove the selected lines: https://github.com/pret/pokeemerald/blob/18980b20a3128b22ab9ba23f2a466d076e95536d/src/battle_controllers.c#L667-L672
- Add the following code here: https://github.com/pret/pokeemerald/blob/18980b20a3128b22ab9ba23f2a466d076e95536d/src/battle_controllers.c#L675
```c
        if (gBattleTypeFlags & BATTLE_TYPE_DOUBLE) {
            u32 playerLeftPos = GetBattlerAtPosition(B_POSITION_PLAYER_LEFT);
            u32 opponentLeftPos = GetBattlerAtPosition(B_POSITION_OPPONENT_LEFT);
            u32 playerRightPos = GetBattlerAtPosition(B_POSITION_PLAYER_RIGHT);
            u32 opponentRightPos = GetBattlerAtPosition(B_POSITION_OPPONENT_RIGHT);
            
            if (gBattlerPartyIndexes[playerRightPos] == 0xff) {
                u32 playerLeftIndex = gBattlerPartyIndexes[playerLeftPos];
                for (i = 0; i < PARTY_SIZE; i++) {
                    u32 species = GetMonData(mon, MON_DATA_SPECIES2);
                    if (species != SPECIES_NONE
                        && species != SPECIES_EGG
                        && GetMonData(mon, MON_DATA_IS_EGG) == 0
                        && i != playerLeftIndex
                    ) {
                        gBattlerPartyIndexes[playerRightPos] = i;
                        break;
                    }
                }

                // either only eggs or 1 size party, so just set index to 0 or 1, depending on player left index
                if (i == PARTY_SIZE) {
                    gBattlerPartyIndexes[playerRightPos] = (playerLeftIndex == 1) ? 0 : 1;
                }
            }

            if (gBattlerPartyIndexes[opponentRightPos] == 0xff) {
                u32 opponentLeftIndex = gBattlerPartyIndexes[opponentLeftPos];
                for (i = 0; i < PARTY_SIZE; i++) {
                    u32 species = GetMonData(mon, MON_DATA_SPECIES2);
                    if (species != SPECIES_NONE
                        && species != SPECIES_EGG
                        && GetMonData(mon, MON_DATA_IS_EGG) == 0
                        && i != opponentLeftIndex
                    ) {
                        gBattlerPartyIndexes[opponentRightPos] = i;
                        break;
                    }
                }
                // same logic as above, although this probably never happens
                if (i == PARTY_SIZE) {
                    gBattlerPartyIndexes[opponentRightPos] = (opponentLeftIndex == 1) ? 0 : 1;
                }
            }
        } else {
            gBattlerPartyIndexes[playerLeftPos] = 0;
            gBattlerPartyIndexes[opponentLeftPos] = 0;
        }
```


- Add the following code here: https://github.com/pret/pokeemerald/blob/18980b20a3128b22ab9ba23f2a466d076e95536d/src/battle_controllers.c#L625
```c
        gBattlerPartyIndexes[0] = 0xff;
        gBattlerPartyIndexes[1] = 0xff;
        gBattlerPartyIndexes[2] = 0xff;
        gBattlerPartyIndexes[3] = 0xff;
```

**Comment by FosterProgramming** [comment]
I think this is fixed and double battle don't start if you have only one alive non-egg mon:

https://github.com/user-attachments/assets/ef605a4d-955a-455f-82f6-102ade775126

**Comment by luckytyphlosion** [comment]
This doesn't fix the issue. The issue is about the option that allows you to start a double battle even if you only have one Pokémon alive.
