### ISSUE TITLE
Resisted EFFECT_RECOIL moves do incorrect recoil damage to the user

### ISSUE THREAD

**Issue by kfmx** [rh-hideout/pokeemerald-expansion#7314]
### Description

**Expected behavior:**
Recoil moves should do the expected amount of recoil to the user. In the case of Double Edge, it should do 33% of the damage dealt.

**Observed behavior:**
When a recoil move is resisted and the target doesn't faint it does more recoil damage to the user than intended.

**Reason for behavior:**
BattleTv_SetDataBasedOnString in battle_tv.c is called after the "It's not very effective..." message, which then calls TrySetBattleSeminarShow...

```
void BattleTv_SetDataBasedOnString(enum StringID stringId)
{
    [...]
    switch (stringId)
    {
    case STRINGID_ITDOESNTAFFECT:
    case STRINGID_ITDOESNTAFFECTTWOFOES:
        AddMovePoints(PTS_EFFECTIVENESS, moveSlot, 2, 0);
        if (!(gBattleTypeFlags & BATTLE_TYPE_LINK))
            TrySetBattleSeminarShow();
        break;
    case STRINGID_NOTVERYEFFECTIVE:
    case STRINGID_NOTVERYEFFECTIVETWOFOES:
        AddMovePoints(PTS_EFFECTIVENESS, moveSlot, 1, 0);
        if (!(gBattleTypeFlags & BATTLE_TYPE_LINK) && GetMonData(defMon, MON_DATA_HP, NULL) != 0)
            TrySetBattleSeminarShow();
        break;
    [...]
}
```

and TrySetBattleSeminarShow changes the value of gBattleStruct->moveDamage[gBattlerTarget], which is what's used for the recoil damage.

```
static void TrySetBattleSeminarShow(void)
{
    [...]
    dmgByMove[gMoveSelectionCursor[gBattlerAttacker]] = gBattleStruct->moveDamage[gBattlerTarget]; // TODO: Not sure
    currMoveSaved = gCurrentMove;
    for (i = 0; i < MAX_MON_MOVES; i++)
    {
        gCurrentMove = gBattleMons[gBattlerAttacker].moves[i];
        powerOverride = 0;
        if (ShouldCalculateDamage(gCurrentMove, &dmgByMove[i], &powerOverride))
        {
            struct DamageCalculationData damageCalcData;
            damageCalcData.battlerAtk = gBattlerAttacker;
            damageCalcData.battlerDef = gBattlerTarget;
            damageCalcData.move = gCurrentMove;
            damageCalcData.moveType = GetMoveType(gCurrentMove);
            damageCalcData.isCrit = FALSE;
            damageCalcData.randomFactor = FALSE;
            damageCalcData.updateFlags = FALSE;
            gBattleStruct->moveDamage[gBattlerTarget] = CalculateMoveDamage(&damageCalcData, powerOverride);
            dmgByMove[i] = gBattleStruct->moveDamage[gBattlerTarget];
            if (dmgByMove[i] == 0 && !(gBattleStruct->moveResultFlags[gBattlerTarget] & MOVE_RESULT_NO_EFFECT))
                dmgByMove[i] = 1;
        }
    }

    for (i = 0; i < MAX_MON_MOVES; i++)
    {
        if (i != gMoveSelectionCursor[gBattlerAttacker] && dmgByMove[i] > dmgByMove[gMoveSelectionCursor[gBattlerAttacker]])
        {
            u16 opponentSpecies, playerSpecies;
            s32 bestMoveId;

            if (gMoveSelectionCursor[gBattlerAttacker] != 0)
                bestMoveId = 0;
            else
                bestMoveId = 1;

            for (i = 0; i < MAX_MON_MOVES; i++)
            {
                if (i != gMoveSelectionCursor[gBattlerAttacker] && dmgByMove[i] > dmgByMove[bestMoveId])
                    bestMoveId = i;
            }

            opponentSpecies = GetMonData(GetBattlerMon(gBattlerTarget),   MON_DATA_SPECIES, NULL);
            playerSpecies   = GetMonData(GetBattlerMon(gBattlerAttacker), MON_DATA_SPECIES, NULL);
            TryPutBattleSeminarOnAir(opponentSpecies, playerSpecies, gMoveSelectionCursor[gBattlerAttacker], gBattleMons[gBattlerAttacker].moves, gBattleMons[gBattlerAttacker].moves[bestMoveId]);
            break;
        }
    }

    gBattleStruct->moveDamage[gBattlerTarget] = dmgByMove[gMoveSelectionCursor[gBattlerAttacker]];
    gCurrentMove = currMoveSaved;
}
```
I haven't done a PR for a fix because I'm not at all familiar with the battle tv stuff and didn't wanna break anything.
In my own project I just commented out the lines that assign to gBattleStruct->moveDamage[gBattlerTarget] and the problem went away.

### Reproduction Steps

1. Start a singles battle
2. Using battle debug, give your mon a recoil move (I used Double Edge)
3. Using battle debug, set the opponents ability to Sturdy, its typing to something that resists your recoil move (I used Rock), and its HP to a low number (I used 3)
4. Use the recoil move

In my case the opponent will correctly survive with 1 HP due to sturdy, taking 2 damage.
The player's mon will then take a larger than normal amount of recoil. In my case it should take 33% of 2, which is rounded to 1. But instead it takes 6.

### Images / Video

A gif of the reproduction steps I explain above

![Image](https://github.com/user-attachments/assets/2d7a1cfd-94d7-4a21-9e2a-d41035e392e1)

### Version

1.12.1 (Latest release)

### Discord contact info

kfmx

**Comment by AlexOn1ine** [comment]
@kfmx Thank you for your detailed bug report! Unfortunately I can't reproduce the issue. Could you point me as to what I'm doing wrong?
```
SINGLE_BATTLE_TEST("Recoil: Resisted recoil damage is correct")
{
    s16 directDamage;
    s16 recoilDamage;

    GIVEN {
        ASSUME(gSpeciesInfo[SPECIES_GEODUDE].types[0] == TYPE_ROCK || gSpeciesInfo[SPECIES_GEODUDE].types[1] == TYPE_ROCK);
        ASSUME(GetMoveRecoil(MOVE_TAKE_DOWN) == 25);
        PLAYER(SPECIES_MEWTWO) { Moves(MOVE_TAKE_DOWN, MOVE_WATER_GUN, MOVE_RAZOR_LEAF, MOVE_FLASH_CANNON); };
        OPPONENT(SPECIES_GEODUDE);
    } WHEN {
        TURN { MOVE(player, MOVE_TAKE_DOWN); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_TAKE_DOWN, player);
        HP_BAR(opponent, captureDamage: &directDamage);
        HP_BAR(player, captureDamage: &recoilDamage);
    } THEN {
        EXPECT_MUL_EQ(directDamage, UQ_4_12(0.25), recoilDamage);
    }
}
```

**Comment by LinathanZel** [comment]
I'm also running into a similar issue but instead it's occurring after living the recoil hit and proccing a recovery item (Sitrus Berry, FIWAM Berry, and Enigma Berry)

https://github.com/user-attachments/assets/d2c42a17-d263-427a-8158-3c71c8433cbc

**Comment by AlexOn1ine** [comment]
> I'm also running into a similar issue but instead it's occurring after living the recoil hit and proccing a recovery item (Sitrus Berry, FIWAM Berry, and Enigma Berry)
> massiverecoil.mp4

This particular issue has been fixed in #7348 but I don't think they are related to the original issue in this ticket.

**Comment by AlexOn1ine** [comment]
I'm closing this because #7348 should have fixed this issue. Please re-open if this is not the case

**Comment by kfmx** [comment]
I just checked this again in the latest 1.12.2 release using my reproduction steps above and the problem is still there.



> [@kfmx](https://github.com/kfmx) Thank you for your detailed bug report! Unfortunately I can't reproduce the issue. Could you point me as to what I'm doing wrong?
> 
> ```
> SINGLE_BATTLE_TEST("Recoil: Resisted recoil damage is correct")
> {
>     s16 directDamage;
>     s16 recoilDamage;
> 
>     GIVEN {
>         ASSUME(gSpeciesInfo[SPECIES_GEODUDE].types[0] == TYPE_ROCK || gSpeciesInfo[SPECIES_GEODUDE].types[1] == TYPE_ROCK);
>         ASSUME(GetMoveRecoil(MOVE_TAKE_DOWN) == 25);
>         PLAYER(SPECIES_MEWTWO) { Moves(MOVE_TAKE_DOWN, MOVE_WATER_GUN, MOVE_RAZOR_LEAF, MOVE_FLASH_CANNON); };
>         OPPONENT(SPECIES_GEODUDE);
>     } WHEN {
>         TURN { MOVE(player, MOVE_TAKE_DOWN); }
>     } SCENE {
>         ANIMATION(ANIM_TYPE_MOVE, MOVE_TAKE_DOWN, player);
>         HP_BAR(opponent, captureDamage: &directDamage);
>         HP_BAR(player, captureDamage: &recoilDamage);
>     } THEN {
>         EXPECT_MUL_EQ(directDamage, UQ_4_12(0.25), recoilDamage);
>     }
> }
> ```

@AlexOn1ine  I don't see Geodude's ability be set to Sturdy anywhere. The opposing Pokémon has to survive the hit for `TrySetBattleSeminarShow` to trigger, so I'm guessing this is the problem.

Also I can't reopen this issue myself since I don't have permissions

**Comment by AlexOn1ine** [comment]
> The opposing Pokémon has to survive the hit for TrySetBattleSeminarShow to trigger, so I'm guessing this is the problem.

I see. I will do further testing, thx.

**Comment by AlexOn1ine** [comment]
@kfmx This looks correct? I'm not sure what I'm doing wrong. Can you provide exact steps you did to reproduce the issue and what numbers you got?

<img width="1085" height="394" alt="Image" src="https://github.com/user-attachments/assets/47b526f9-7903-4ba6-8bb0-5fdba20ad43f" />

**Comment by kfmx** [comment]
@AlexOn1ine This looks correct except that the opposing Mewtwo seems to be the one using the recoil move?

When I tested I always had the player's Pokémon be the one to use the recoil move.
I just tested again with the opposing Pokémon using the recoil move and I didn't have an issue.

I took a peek at the function `TrySetBattleSeminarShow` and on line 1226 it seems to exit early if the attacking mon is not on the player's side:
```
    else if (!IsOnPlayerSide(gBattlerAttacker))
        return;
```
So it would seem this bug only occurs when the Pokémon using the recoil move is on the player's side.

**Comment by AlexOn1ine** [comment]
> [@AlexOn1ine](https://github.com/AlexOn1ine) This looks correct except that the opposing Mewtwo seems to be the one using the recoil move?
> 
> When I tested I always had the player's Pokémon be the one to use the recoil move. I just tested again with the opposing Pokémon using the recoil move and I didn't have an issue.
> 
> I took a peek at the function `TrySetBattleSeminarShow` and on line 1226 it seems to exit early if the attacking mon is not on the player's side:
> 
> ```
>     else if (!IsOnPlayerSide(gBattlerAttacker))
>         return;
> ```
> 
> So it would seem this bug only occurs when the Pokémon using the recoil move is on the player's side.

ah this makes sense now
